[package]
name = "skope_gltf"
version.workspace = true
edition.workspace = true

[dependencies]
gltf = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
rayon = { workspace = true, optional = true }

[features]
default = []
parallel = ["rayon"]
