//! Widget system for skope_ui

mod traits;
mod slot;
mod slot_types;
mod combined_children;
mod null_widget;
mod s_box;
mod s_border;
mod s_button;
mod s_box_panel;
mod s_text_block;
mod s_image;
mod s_scroll_box;
mod s_list_view;
mod s_check_box;
mod s_slider;
mod s_spin_box;
mod s_editable_text_box;
mod s_combo_box;
mod s_tree_view;
mod s_grid_panel;
mod s_splitter;
mod s_menu_anchor;
mod s_menu;
mod s_progress_bar;
mod s_expandable_area;
mod s_search_box;
mod s_vector_input_box;
mod s_color_wheel;
mod s_multi_line_editable_text_box;
mod s_menu_bar;
mod s_overlay;
mod s_widget_switcher;
mod s_rich_text_block;
mod s_spacer;
mod s_separator;
mod s_canvas;
mod s_wrap_box;
mod s_header_row;
mod s_breadcrumb_trail;
mod s_dpi_scaler;
mod s_fx_widget;
mod s_multi_box_toolbar;
// Phase 5: P3#24-26 누락 위젯
mod s_color_block;
mod s_simple_gradient;
mod s_error_text;
mod s_scissor_rect_box;
mod s_safe_zone;
mod s_scale_box;
mod s_stack_box;
mod s_uniform_grid_panel;
mod s_radial_box;
mod s_hyperlink;
mod s_throbber;
mod s_expandable_button;
mod s_window_title_bar_area;
mod s_numeric_entry_box;
mod s_editable_label;
mod s_inline_editable_text_block;
mod s_text_scroller;
mod s_segmented_control;
mod s_popup;
mod s_combo_button;
// Phase 11: 입력 위젯
mod s_numeric_drop_down;
mod s_volume_control;
mod s_editable_text_trait;
mod s_editable_combo_box;
mod s_input_key_selector;
mod s_suggestion_text_box;
mod s_virtual_joystick;
// Phase 12: 뷰/색상/복합 위젯
mod s_table_view_base;
mod s_table_row;
mod s_tile_view;
mod s_color_spectrum;
mod s_color_grading_wheel;
mod s_tool_tip;
mod s_layer_manager;
mod s_viewport_widget;
// P0#3: 툴바/클리핑 위젯
mod s_toolbar_combo_button_block;
mod s_toolbar_stack_button_block;
mod s_clipping_horizontal_box;
mod s_prioritized_wrap_box;
// Phase 10: 레이아웃 위젯
mod s_uniform_wrap_panel;
mod s_linked_box;
mod s_invalidation_panel;
mod s_background_blur;
mod s_constraint_canvas;
mod s_responsive_grid_panel;

pub use traits::*;
pub use slot::*;
pub use slot_types::*;
pub use combined_children::*;
pub use null_widget::*;
pub use s_box::*;
pub use s_border::*;
pub use s_button::*;
pub use s_box_panel::*;
pub use s_text_block::*;
pub use s_image::*;
pub use s_scroll_box::*;
pub use s_list_view::*;
pub use s_check_box::*;
pub use s_slider::*;
pub use s_spin_box::*;
pub use s_editable_text_box::*;
pub use s_combo_box::*;
pub use s_tree_view::*;
pub use s_grid_panel::*;
pub use s_splitter::*;
pub use s_menu_anchor::*;
pub use s_menu::*;
pub use s_progress_bar::*;
pub use s_expandable_area::*;
pub use s_search_box::*;
pub use s_vector_input_box::*;
pub use s_color_wheel::*;
pub use s_multi_line_editable_text_box::*;
pub use s_menu_bar::*;
pub use s_overlay::*;
pub use s_widget_switcher::*;
pub use s_rich_text_block::*;
pub use s_spacer::*;
pub use s_separator::*;
pub use s_canvas::*;
pub use s_wrap_box::*;
pub use s_header_row::*;
pub use s_breadcrumb_trail::*;
pub use s_dpi_scaler::*;
pub use s_fx_widget::*;
pub use s_multi_box_toolbar::*;
pub use s_color_block::*;
pub use s_simple_gradient::*;
pub use s_error_text::*;
pub use s_scissor_rect_box::*;
pub use s_safe_zone::*;
pub use s_scale_box::*;
pub use s_stack_box::*;
pub use s_uniform_grid_panel::*;
pub use s_radial_box::*;
pub use s_hyperlink::*;
pub use s_throbber::*;
pub use s_expandable_button::*;
pub use s_window_title_bar_area::*;
pub use s_numeric_entry_box::*;
pub use s_editable_label::*;
pub use s_inline_editable_text_block::*;
pub use s_text_scroller::*;
pub use s_segmented_control::*;
pub use s_popup::*;
pub use s_combo_button::*;
pub use s_toolbar_combo_button_block::*;
pub use s_toolbar_stack_button_block::*;
pub use s_clipping_horizontal_box::*;
pub use s_prioritized_wrap_box::*;
pub use s_uniform_wrap_panel::*;
pub use s_linked_box::*;
pub use s_invalidation_panel::*;
pub use s_background_blur::*;
pub use s_constraint_canvas::*;
pub use s_responsive_grid_panel::*;
pub use s_numeric_drop_down::*;
pub use s_volume_control::*;
pub use s_editable_text_trait::*;
pub use s_editable_combo_box::*;
pub use s_input_key_selector::*;
pub use s_suggestion_text_box::*;
pub use s_virtual_joystick::*;
pub use s_table_view_base::*;
pub use s_table_row::*;
pub use s_tile_view::*;
pub use s_color_spectrum::*;
pub use s_color_grading_wheel::*;
pub use s_tool_tip::*;
pub use s_layer_manager::*;
pub use s_viewport_widget::*;

// Re-export SizeRule from core
pub use crate::core::SizeRule;
